#!/usr/bin/env bash
# runner.sh — auto-generated by claude-skill-distill
# Skill: mitmproxy-mitmdump
# Tool check: which mitmdump
# Validated against base digest: sha256:f9c6a2fd2ddbc23e336b6257a5245e31f996953ef06cd13a59fa0a1df2d5c252
#
# Substitution contract (T4 distill build stage):
# - mitmproxy-mitmdump       : alphanumeric + hyphens; injected raw
# - which mitmdump       : bash expression run via `bash -c '...'`;
#                          substitution must escape `'` but may contain
#                          $/`/" safely inside single quotes
# - sha256:f9c6a2fd2ddbc23e336b6257a5245e31f996953ef06cd13a59fa0a1df2d5c252 : sha256:... string; injected raw (40+8 hex chars)
set -euo pipefail
SKILL_DIR="$(cd "$(dirname "$0")" && pwd)"
SANDBOX="${CLAUDE_SKILL_SANDBOX:-claude-skill-sandbox}"
BASE_IMAGE="${CLAUDE_SKILL_BASE:-debian:12-slim}"
STATE_VOL="${CLAUDE_SKILL_STATE_VOL:-claude-skill-state}"

# Translate a host path under $HOME to its /host_home/* equivalent.
# Returns 1 if path is outside $HOME (caller falls back to copy-in/cp-out).
to_in_container_path() {
  local p="$1"
  case "$p" in
    "$HOME") printf '%s' '/host_home' ;;
    "$HOME"/*) printf '/host_home%s' "${p#"$HOME"}" ;;
    *) return 1 ;;
  esac
}

# 0. Preflight
docker info >/dev/null 2>&1 || {
  echo "[claude-skill] docker daemon not reachable. Start Docker Desktop and retry." >&2
  exit 2
}

# 1. 容器懒创建
if ! docker ps -a --format '{{.Names}}' | grep -q "^${SANDBOX}$"; then
  docker volume create "$STATE_VOL" >/dev/null
  docker run -d --name "$SANDBOX" --restart=unless-stopped \
    --mount type=volume,source="$STATE_VOL",target=/state \
    --mount type=bind,source="$HOME",target=/host_home \
    "$BASE_IMAGE" sleep infinity >/dev/null
fi

# 2. 容器停止时启动
if ! docker ps --format '{{.Names}}' | grep -q "^${SANDBOX}$"; then
  docker start "$SANDBOX" >/dev/null
fi

# 3. Drift 检测（不阻断）
CURRENT=$(docker image inspect "$BASE_IMAGE" --format '{{.Id}}' 2>/dev/null || echo "")
if [ -n "$CURRENT" ] && [ "$CURRENT" != "sha256:f9c6a2fd2ddbc23e336b6257a5245e31f996953ef06cd13a59fa0a1df2d5c252" ]; then
  echo "[claude-skill] base image drifted from validated digest. If scripts misbehave, run claude-skill-sandbox validate mitmproxy-mitmdump" >&2
fi

# 4. 工具懒装入
if ! docker exec "$SANDBOX" bash -c 'which mitmdump' >/dev/null 2>&1; then
  docker exec -e DEBIAN_FRONTEND=noninteractive "$SANDBOX" bash "$(to_in_container_path "$SKILL_DIR")/install.sh"
fi

# 5. cwd 翻译
if IN_CWD=$(to_in_container_path "$PWD"); then
  CLEANUP=""
else
  echo "[claude-skill] \$PWD outside \$HOME, using copy-in/cp-out fallback" >&2
  TMPID=$(uuidgen 2>/dev/null | tr -d '-' | head -c 12 || date +%s%N)
  IN_CWD="/tmp/work-$TMPID"
  docker exec "$SANDBOX" mkdir -p "$IN_CWD"
  docker cp "$PWD/." "$SANDBOX:$IN_CWD/"
  CLEANUP='docker cp "$SANDBOX:$IN_CWD/." "$PWD/" 2>/dev/null; docker exec "$SANDBOX" rm -rf "$IN_CWD"'
  trap "$CLEANUP" EXIT
fi

# 6. 记录使用
docker exec "$SANDBOX" bash -c "mkdir -p /state/manifests && echo \"\$(date -Iseconds) mitmproxy-mitmdump\" >> /state/manifests/usage.log"

# 7. 执行
docker exec -i -w "$IN_CWD" "$SANDBOX" \
  bash "$(to_in_container_path "$SKILL_DIR")/run-impl.sh" "$@"
